AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 'sts:AssumeRole'
            Principal:
              Service: 'lambda.amazonaws.com'
      Policies:
        - PolicyName: 'LambdaGluePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'glue:StartJobRun'
                Resource: '*'

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: 'GlueJobLambdaFunction'
      Code:
        S3Bucket: 'websiteupload01'  # Specify the S3 bucket where your code is stored
        S3Key: 'path/to/your/code.zip'  # Specify the S3 key (file path) of your Lambda function code
      Runtime: 'python3.8'
      Environment:
        Variables:
          GLUE_JOB_NAME: 'MyGlueJob'  # Set the Glue Job name here
      Timeout: 300  # Set an appropriate timeout

Outputs:
  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt LambdaFunction.Arn
